---
title: "Multivariate Smooths via glmmTMB"
author: "e.dovers@unsw.edu.au"
date: '2023'
---

```{r get_data, include=FALSE}
library(glmmTMB)
# load in the relevant models
load("3D_stuff.RDATA")
# library(knitr)
# library(rgl)
# knitr::knit_hooks$set(webgl = hook_webgl)
```

<!-- ```{r, setup} -->
<!-- library(rgl) -->
<!-- options(rgl.useNULL = TRUE) # Suppress the separate window. -->
<!-- setupKnitr(autoprint = TRUE) -->
<!-- ``` -->

```{r}
library(rgl)
options(rgl.useNULL = TRUE) # Suppress the separate window.
setupKnitr(autoprint = TRUE)
all_lims <- range(scores[,1:3])
scale.loads <- 0.75
plot3d(scores[,1:3], xlim = all_lims, ylim = all_lims, zlim = all_lims, col = bf.cols, pch = 16, size = 8, xlab = expression(u[1]), ylab = expression(u[2]),zlab = expression(u[3]))
# for (sp in 1:length(species)) {
#   if (sp %in% selected.sp) {
#     arrow3d(c(0,0,0), loads[sp,] * scale.loads, type = "lines", col = "black", s = 0.05)
#     text3d((loads[sp,] * scale.loads) + (0.2 * sign(loads[sp,])), texts = sp.info$nice.names[sp], cex = 1.5)
#   } else {
#     arrow3d(c(0,0,0), loads[sp,] * scale.loads, type = "lines", col = "grey50", s = 0)
#   }
# }
# rglwidget()
```

<!-- ```{r, echo=FALSE, webgl=TRUE} -->
<!-- all_lims <- range(scores[,1:3]) -->
<!-- scale.loads <- 0.75 -->
<!-- plot3d(scores[,1:3], xlim = all_lims, ylim = all_lims, zlim = all_lims, -->
<!--        col = bf.cols, pch = 16, size = 8, -->
<!--        xlab = expression(u[1]), ylab = expression(u[2]), zlab = expression(u[3]) -->
<!-- ) -->
<!-- for (sp in 1:length(species)) { -->
<!--   if (sp %in% selected.sp) { -->
<!--     arrow3d(c(0,0,0), loads[sp,] * scale.loads, type = "lines", col = "black", s = 0.05) -->
<!--     text3d((loads[sp,] * scale.loads) + (0.2 * sign(loads[sp,])), texts = sp.info$nice.names[sp], cex = 1.5) -->
<!--   } else { -->
<!--     arrow3d(c(0,0,0), loads[sp,] * scale.loads, type = "lines", col = "grey50", s = 0) -->
<!--   } -->
<!-- } -->
<!-- ``` -->

